import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import ThemeProvider from "@/providers/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import ToastProvider from "@/providers/toast-provider";
import QueryProvider from "@/providers/query-provider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "WaveChat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={manrope.variable} suppressHydrationWarning>
      <body>
        <QueryProvider>
          <ThemeProvider>
            <TooltipProvider>
              <ToastProvider>{children}</ToastProvider>
            </TooltipProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
